# Generated by Django 5.2.6 on 2025-09-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('sepatu', 'Sepatu'), ('celana', 'Celana'), ('bola', 'Bola'), ('lain lain', 'Lain Lain')], default='update')),
            ],
        ),
    ]
